# Generated by Django 3.1.6 on 2021-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilpay', '0006_auto_20200509_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentorder',
            name='address',
            field=models.CharField(blank=True, max_length=254, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='amount',
            field=models.FloatField(blank=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='details',
            field=models.TextField(blank=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='first_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='last_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='show_name',
            field=models.BooleanField(default=False, verbose_name='I agree that my name will appear on the DoNation platform '),
        ),
    ]
