# Generated by Django 3.1.6 on 2021-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0048_auto_20200429_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='county',
            field=models.CharField(choices=[('DELHI', 'DELHI'), ('ARAD', 'ARAD'), ('ARGES', 'ARGES'), ('BACAU', 'BACAU'), ('BIHOR', 'BIHOR'), ('BISTRITA-NASAUD', 'BISTRITA-NASAUD'), ('BOTOSANI', 'BOTOSANI'), ('BRAILA', 'BRAILA'), ('BRASOV', 'BRASOV'), ('BUCURESTI', 'BUCURESTI'), ('BUZAU', 'BUZAU'), ('CARAS-SEVERIN', 'CARAS-SEVERIN'), ('CALARASI', 'CALARASI'), ('CLUJ', 'CLUJ'), ('CONSTANTA', 'CONSTANTA'), ('COVASNA', 'COVASNA'), ('DAMBOVITA', 'DAMBOVITA'), ('DOLJ', 'DOLJ'), ('GALATI', 'GALATI'), ('GIURGIU', 'GIURGIU'), ('GORJ', 'GORJ'), ('HARGHITA', 'HARGHITA'), ('HUNEDOARA', 'HUNEDOARA'), ('IALOMITA', 'IALOMITA'), ('IASI', 'IASI'), ('ILFOV', 'ILFOV'), ('MARAMURES', 'MARAMURES'), ('MEHEDINTI', 'MEHEDINTI'), ('MURES', 'MURES'), ('NEAMT', 'NEAMT'), ('OLT', 'OLT'), ('PRAHOVA', 'PRAHOVA'), ('SATU MARE', 'SATU MARE'), ('SALAJ', 'SALAJ'), ('SIBIU', 'SIBIU'), ('SUCEAVA', 'SUCEAVA'), ('TELEORMAN', 'TELEORMAN'), ('TIMIS', 'TIMIS'), ('TULCEA', 'TULCEA'), ('VASLUI', 'VASLUI'), ('VALCEA', 'VALCEA'), ('VRANCEA', 'VRANCEA')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='ngoaccount',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('EUR', 'EUR'), ('USD', 'USD')], default='INR', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='ngoneed',
            name='county',
            field=models.CharField(choices=[('DELHI', 'DELHI'), ('ARAD', 'ARAD'), ('ARGES', 'ARGES'), ('BACAU', 'BACAU'), ('BIHOR', 'BIHOR'), ('BISTRITA-NASAUD', 'BISTRITA-NASAUD'), ('BOTOSANI', 'BOTOSANI'), ('BRAILA', 'BRAILA'), ('BRASOV', 'BRASOV'), ('BUCURESTI', 'BUCURESTI'), ('BUZAU', 'BUZAU'), ('CARAS-SEVERIN', 'CARAS-SEVERIN'), ('CALARASI', 'CALARASI'), ('CLUJ', 'CLUJ'), ('CONSTANTA', 'CONSTANTA'), ('COVASNA', 'COVASNA'), ('DAMBOVITA', 'DAMBOVITA'), ('DOLJ', 'DOLJ'), ('GALATI', 'GALATI'), ('GIURGIU', 'GIURGIU'), ('GORJ', 'GORJ'), ('HARGHITA', 'HARGHITA'), ('HUNEDOARA', 'HUNEDOARA'), ('IALOMITA', 'IALOMITA'), ('IASI', 'IASI'), ('ILFOV', 'ILFOV'), ('MARAMURES', 'MARAMURES'), ('MEHEDINTI', 'MEHEDINTI'), ('MURES', 'MURES'), ('NEAMT', 'NEAMT'), ('OLT', 'OLT'), ('PRAHOVA', 'PRAHOVA'), ('SATU MARE', 'SATU MARE'), ('SALAJ', 'SALAJ'), ('SIBIU', 'SIBIU'), ('SUCEAVA', 'SUCEAVA'), ('TELEORMAN', 'TELEORMAN'), ('TIMIS', 'TIMIS'), ('TULCEA', 'TULCEA'), ('VASLUI', 'VASLUI'), ('VALCEA', 'VALCEA'), ('VRANCEA', 'VRANCEA')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='ngoreportitem',
            name='amount',
            field=models.FloatField(verbose_name='Amount spent (INR)'),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='county',
            field=models.CharField(choices=[('DELHI', 'DELHI'), ('ARAD', 'ARAD'), ('ARGES', 'ARGES'), ('BACAU', 'BACAU'), ('BIHOR', 'BIHOR'), ('BISTRITA-NASAUD', 'BISTRITA-NASAUD'), ('BOTOSANI', 'BOTOSANI'), ('BRAILA', 'BRAILA'), ('BRASOV', 'BRASOV'), ('BUCURESTI', 'BUCURESTI'), ('BUZAU', 'BUZAU'), ('CARAS-SEVERIN', 'CARAS-SEVERIN'), ('CALARASI', 'CALARASI'), ('CLUJ', 'CLUJ'), ('CONSTANTA', 'CONSTANTA'), ('COVASNA', 'COVASNA'), ('DAMBOVITA', 'DAMBOVITA'), ('DOLJ', 'DOLJ'), ('GALATI', 'GALATI'), ('GIURGIU', 'GIURGIU'), ('GORJ', 'GORJ'), ('HARGHITA', 'HARGHITA'), ('HUNEDOARA', 'HUNEDOARA'), ('IALOMITA', 'IALOMITA'), ('IASI', 'IASI'), ('ILFOV', 'ILFOV'), ('MARAMURES', 'MARAMURES'), ('MEHEDINTI', 'MEHEDINTI'), ('MURES', 'MURES'), ('NEAMT', 'NEAMT'), ('OLT', 'OLT'), ('PRAHOVA', 'PRAHOVA'), ('SATU MARE', 'SATU MARE'), ('SALAJ', 'SALAJ'), ('SIBIU', 'SIBIU'), ('SUCEAVA', 'SUCEAVA'), ('TELEORMAN', 'TELEORMAN'), ('TIMIS', 'TIMIS'), ('TULCEA', 'TULCEA'), ('VASLUI', 'VASLUI'), ('VALCEA', 'VALCEA'), ('VRANCEA', 'VRANCEA')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='county',
            field=models.CharField(choices=[('DELHI', 'DELHI'), ('ARAD', 'ARAD'), ('ARGES', 'ARGES'), ('BACAU', 'BACAU'), ('BIHOR', 'BIHOR'), ('BISTRITA-NASAUD', 'BISTRITA-NASAUD'), ('BOTOSANI', 'BOTOSANI'), ('BRAILA', 'BRAILA'), ('BRASOV', 'BRASOV'), ('BUCURESTI', 'BUCURESTI'), ('BUZAU', 'BUZAU'), ('CARAS-SEVERIN', 'CARAS-SEVERIN'), ('CALARASI', 'CALARASI'), ('CLUJ', 'CLUJ'), ('CONSTANTA', 'CONSTANTA'), ('COVASNA', 'COVASNA'), ('DAMBOVITA', 'DAMBOVITA'), ('DOLJ', 'DOLJ'), ('GALATI', 'GALATI'), ('GIURGIU', 'GIURGIU'), ('GORJ', 'GORJ'), ('HARGHITA', 'HARGHITA'), ('HUNEDOARA', 'HUNEDOARA'), ('IALOMITA', 'IALOMITA'), ('IASI', 'IASI'), ('ILFOV', 'ILFOV'), ('MARAMURES', 'MARAMURES'), ('MEHEDINTI', 'MEHEDINTI'), ('MURES', 'MURES'), ('NEAMT', 'NEAMT'), ('OLT', 'OLT'), ('PRAHOVA', 'PRAHOVA'), ('SATU MARE', 'SATU MARE'), ('SALAJ', 'SALAJ'), ('SIBIU', 'SIBIU'), ('SUCEAVA', 'SUCEAVA'), ('TELEORMAN', 'TELEORMAN'), ('TIMIS', 'TIMIS'), ('TULCEA', 'TULCEA'), ('VASLUI', 'VASLUI'), ('VALCEA', 'VALCEA'), ('VRANCEA', 'VRANCEA')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='description',
            field=models.TextField(help_text="Organi zation's short description - max 500 chars.", max_length=500, verbose_name='Description'),
        ),
    ]
