# Generated by Django 3.1.6 on 2021-02-13 12:22

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0049_auto_20210213_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerngorequest',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='address',
            field=models.CharField(blank=True, max_length=400, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Image should be 500x500px', max_length=300, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='contact_name',
            field=models.CharField(blank=True, max_length=254, verbose_name="Contact person's name"),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name="Contact person's phone"),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='county',
            field=models.CharField(blank=True, choices=[('DELHI', 'DELHI'), ('ARAD', 'ARAD'), ('ARGES', 'ARGES'), ('BACAU', 'BACAU'), ('BIHOR', 'BIHOR'), ('BISTRITA-NASAUD', 'BISTRITA-NASAUD'), ('BOTOSANI', 'BOTOSANI'), ('BRAILA', 'BRAILA'), ('BRASOV', 'BRASOV'), ('BUCURESTI', 'BUCURESTI'), ('BUZAU', 'BUZAU'), ('CARAS-SEVERIN', 'CARAS-SEVERIN'), ('CALARASI', 'CALARASI'), ('CLUJ', 'CLUJ'), ('CONSTANTA', 'CONSTANTA'), ('COVASNA', 'COVASNA'), ('DAMBOVITA', 'DAMBOVITA'), ('DOLJ', 'DOLJ'), ('GALATI', 'GALATI'), ('GIURGIU', 'GIURGIU'), ('GORJ', 'GORJ'), ('HARGHITA', 'HARGHITA'), ('HUNEDOARA', 'HUNEDOARA'), ('IALOMITA', 'IALOMITA'), ('IASI', 'IASI'), ('ILFOV', 'ILFOV'), ('MARAMURES', 'MARAMURES'), ('MEHEDINTI', 'MEHEDINTI'), ('MURES', 'MURES'), ('NEAMT', 'NEAMT'), ('OLT', 'OLT'), ('PRAHOVA', 'PRAHOVA'), ('SATU MARE', 'SATU MARE'), ('SALAJ', 'SALAJ'), ('SIBIU', 'SIBIU'), ('SUCEAVA', 'SUCEAVA'), ('TELEORMAN', 'TELEORMAN'), ('TIMIS', 'TIMIS'), ('TULCEA', 'TULCEA'), ('VASLUI', 'VASLUI'), ('VALCEA', 'VALCEA'), ('VRANCEA', 'VRANCEA')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='description',
            field=models.TextField(blank=True, help_text="Organi zation's short description - max 500 chars.", max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='has_netopia_contract',
            field=models.BooleanField(blank=True, default=False, verbose_name='Has contract with Netopia'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='last_balance_sheet',
            field=models.FileField(blank=True, max_length=300, storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='First page of last balance sheet'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='past_actions',
            field=models.TextField(blank=True, help_text='Description of past actions, with empahsis on COVID-19 related actions.', max_length=500, verbose_name='Past actions'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='resource_types',
            field=models.TextField(blank=True, help_text='The types of resources you anticipate you will need.', max_length=500, verbose_name='Resource tags'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='statute',
            field=models.FileField(blank=True, max_length=300, storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='NGO Statute'),
        ),
    ]
