# Generated by Django 3.1.6 on 2021-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0052_auto_20210215_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='county',
            field=models.CharField(choices=[('D', 'D'), ('H', 'H'), ('PUNJAB', 'PUNJAB'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('BIHAR', 'BIHAR'), ('ARUNACHAL', 'ARUNACHAL'), ('ASSAM', 'ASSAM'), ('CHATTISHGARH', 'CHATTISHGARH'), ('GUJRAT', 'GUJRAT'), ('HIMACHAL', 'HIMACHAL'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERELA', 'KERELA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('ODHISA', 'ODHISA'), ('SIKKIM', 'SIKKIM'), ('GIURGIU', 'GIURGIU'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UP', 'UP'), ('UTTRAKHAND', 'UTTRAKHAND'), ('WEST BENGAL', 'WEST BENGAL')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='ngoneed',
            name='county',
            field=models.CharField(choices=[('D', 'D'), ('H', 'H'), ('PUNJAB', 'PUNJAB'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('BIHAR', 'BIHAR'), ('ARUNACHAL', 'ARUNACHAL'), ('ASSAM', 'ASSAM'), ('CHATTISHGARH', 'CHATTISHGARH'), ('GUJRAT', 'GUJRAT'), ('HIMACHAL', 'HIMACHAL'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERELA', 'KERELA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('ODHISA', 'ODHISA'), ('SIKKIM', 'SIKKIM'), ('GIURGIU', 'GIURGIU'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UP', 'UP'), ('UTTRAKHAND', 'UTTRAKHAND'), ('WEST BENGAL', 'WEST BENGAL')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='county',
            field=models.CharField(choices=[('D', 'D'), ('H', 'H'), ('PUNJAB', 'PUNJAB'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('BIHAR', 'BIHAR'), ('ARUNACHAL', 'ARUNACHAL'), ('ASSAM', 'ASSAM'), ('CHATTISHGARH', 'CHATTISHGARH'), ('GUJRAT', 'GUJRAT'), ('HIMACHAL', 'HIMACHAL'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERELA', 'KERELA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('ODHISA', 'ODHISA'), ('SIKKIM', 'SIKKIM'), ('GIURGIU', 'GIURGIU'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UP', 'UP'), ('UTTRAKHAND', 'UTTRAKHAND'), ('WEST BENGAL', 'WEST BENGAL')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='county',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('H', 'H'), ('PUNJAB', 'PUNJAB'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('BIHAR', 'BIHAR'), ('ARUNACHAL', 'ARUNACHAL'), ('ASSAM', 'ASSAM'), ('CHATTISHGARH', 'CHATTISHGARH'), ('GUJRAT', 'GUJRAT'), ('HIMACHAL', 'HIMACHAL'), ('JHARKHAND', 'JHARKHAND'), ('KARNATAKA', 'KARNATAKA'), ('KERELA', 'KERELA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('MAHARASHTRA', 'MAHARASHTRA'), ('MANIPUR', 'MANIPUR'), ('MEGHALAYA', 'MEGHALAYA'), ('ODHISA', 'ODHISA'), ('SIKKIM', 'SIKKIM'), ('GIURGIU', 'GIURGIU'), ('TAMIL NADU', 'TAMIL NADU'), ('TELANGANA', 'TELANGANA'), ('TRIPURA', 'TRIPURA'), ('UP', 'UP'), ('UTTRAKHAND', 'UTTRAKHAND'), ('WEST BENGAL', 'WEST BENGAL')], max_length=50, verbose_name='County'),
        ),
    ]
