# Generated by Django 3.1.6 on 2021-02-16 14:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0055_auto_20210216_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngohelper',
            name='image',
        ),
        migrations.AddField(
            model_name='ngohelper',
            name='resource_image',
            field=models.ImageField(blank=True, help_text='Images should be  more than 500x500px and should be of good quality', storage=django.core.files.storage.FileSystemStorage(), upload_to='path/', verbose_name='Resource Images'),
        ),
    ]
