# Generated by Django 3.1.6 on 2021-02-18 11:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0058_auto_20210217_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngohelper',
            name='resource_image',
            field=models.ImageField(blank=True, help_text='Images should be  more than 500x500px and should be of good quality', storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='Resource Images'),
        ),
    ]
