# Generated by Django 3.1.6 on 2021-02-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0059_auto_20210218_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngohelper',
            name='resource_image',
            field=models.FileField(blank=True, help_text='Images should be  more than 500x500px and should be of good quality', max_length=300, upload_to='', verbose_name='Resource Images'),
        ),
        migrations.AlterField(
            model_name='registerngorequest',
            name='avatar',
            field=models.ImageField(help_text='Image should be 500x500px', max_length=300, upload_to='', verbose_name='Avatar'),
        ),
    ]
