# Generated by Django 3.1.6 on 2021-02-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0060_auto_20210218_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngohelper',
            name='resource_image',
            field=models.ImageField(blank=True, help_text='Images should be  more than 500x500px and should be of good quality', max_length=300, upload_to='', verbose_name='Resource Images'),
        ),
    ]
